name: Build

on: 
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: Build appimagetool
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ARCH: 'x86_64'
            docker-image: 'appimagebuild'
          - ARCH: 'i686'
            docker-image: 'appimagebuild-i386'
          - ARCH: 'armhf'
            docker-image: 'appimagebuild-armhf-cross'
          - ARCH: 'aarch64'
            docker-image: 'appimagebuild-aarch64-cross'

    env:
      DOCKER_IMAGE: quay.io/appimage/${{ matrix.docker-image }}
      ARCH: ${{ matrix.ARCH }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU integration for Docker
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build 
        run: |
          bash -ex ci/build.sh

      - name: List files
        run: |
          ls -lh build/out/*

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: appimagetool-${{ matrix.ARCH }}.build
          path: build/out


  upload:
    needs: [build]
    runs-on: ubuntu-latest
 
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage **/appimagetool*.AppImage*

